"""
Configuration management for agentsync.
Reads/writes .agentsync/config.toml and .agentsync/rules.md
Zero external dependencies — uses stdlib tomllib (Python 3.11+) with fallback.
"""

from __future__ import annotations

import sys
from dataclasses import dataclass, field
from pathlib import Path

if sys.version_info >= (3, 11):
    import tomllib
else:
    try:
        import tomllib  # type: ignore[no-redef]
    except ImportError:
        tomllib = None  # type: ignore[assignment]

AGENTSYNC_DIR = ".agentsync"
CONFIG_FILE = ".agentsync/config.toml"
RULES_FILE = ".agentsync/rules.md"
LOCK_FILE = ".agentsync/agentsync.lock"

DEFAULT_CONFIG = """\
# agentsync configuration
# Edit this file to control which tools receive generated rule files.
# Run `agentsync sync` after any change.

[agentsync]
version = "1.0.0"
canonical = ".agentsync/rules.md"

# Tools to generate rule files for.
# Available: agents_md, claude_md, cursorrules, cursor_mdc, copilot,
#            gemini_md, windsurf, aider, opencode
tools = [
    "agents_md",
    "claude_md",
    "cursorrules",
    "cursor_mdc",
    "copilot",
    "gemini_md",
    "windsurf",
]

# Add generated files to .gitignore automatically
auto_gitignore = true

# Warn if rule files exist that were not generated by agentsync
warn_unmanaged = true
"""

DEFAULT_RULES = """\
# Project Rules

> This file is the single source of truth for all AI coding agent rules.
> Edit this file, then run `agentsync sync` to propagate changes to all tools.
> Generated files: AGENTS.md, CLAUDE.md, .cursorrules, .cursor/rules/main.mdc,
>                  .github/copilot-instructions.md, GEMINI.md, .windsurfrules

## Stack

<!-- Describe your tech stack here -->
- Language: Python 3.11+
- Framework: (your framework)
- Package manager: pip / uv

## Code conventions

<!-- Add your coding conventions here -->
- Follow PEP 8 for Python code
- Use type hints throughout
- Write docstrings for all public functions

## Testing

<!-- Describe your test setup -->
- Run tests with: pytest tests/ -v
- All new features need tests
- Maintain >80% coverage

## Project structure

<!-- Describe key directories and their purpose -->
- `src/` — application source code
- `tests/` — test suite
- `docs/` — documentation

## Build and deploy

<!-- Key commands -->
- Install: pip install -e ".[dev]"
- Test: pytest tests/
- Lint: ruff check src/ && black --check src/

## Important constraints

<!-- Rules the AI must follow -->
- Never commit secrets or credentials
- Always run tests before suggesting a PR
- Ask before refactoring across multiple files
"""


@dataclass
class AgentSyncConfig:
    """Parsed agentsync configuration."""

    version: str = "1.0.0"
    canonical: str = RULES_FILE
    tools: list[str] = field(
        default_factory=lambda: [
            "agents_md",
            "claude_md",
            "cursorrules",
            "cursor_mdc",
            "copilot",
            "gemini_md",
            "windsurf",
        ]
    )
    auto_gitignore: bool = True
    warn_unmanaged: bool = True
    root: Path = field(default_factory=Path.cwd)

    @property
    def canonical_path(self) -> Path:
        return self.root / self.canonical

    @property
    def config_path(self) -> Path:
        return self.root / CONFIG_FILE

    @property
    def lock_path(self) -> Path:
        return self.root / LOCK_FILE

    def __repr__(self) -> str:
        return f"AgentSyncConfig(tools={self.tools}, canonical={self.canonical!r})"


def load_config(root: Path | None = None) -> AgentSyncConfig:
    """Load agentsync config from .agentsync/config.toml."""
    root = root or Path.cwd()
    config_path = root / CONFIG_FILE
    cfg = AgentSyncConfig(root=root)

    if not config_path.exists():
        return cfg

    if tomllib is None:
        # Python 3.10 fallback — manual TOML parsing for our simple format
        return _parse_config_manual(config_path, root)

    try:
        data = tomllib.loads(config_path.read_text(encoding="utf-8"))
        section = data.get("agentsync", {})
        cfg.version = section.get("version", cfg.version)
        cfg.canonical = section.get("canonical", cfg.canonical)
        cfg.tools = section.get("tools", cfg.tools)
        cfg.auto_gitignore = section.get("auto_gitignore", cfg.auto_gitignore)
        cfg.warn_unmanaged = section.get("warn_unmanaged", cfg.warn_unmanaged)
    except Exception:
        pass

    return cfg


def _parse_config_manual(config_path: Path, root: Path) -> AgentSyncConfig:
    """Minimal TOML parser for Python 3.10 compatibility."""
    cfg = AgentSyncConfig(root=root)
    try:
        text = config_path.read_text(encoding="utf-8")
        for line in text.splitlines():
            line = line.strip()
            if line.startswith("tools"):
                # Extract list of quoted strings
                import re

                tools = re.findall(r'"([^"]+)"', line)
                if tools:
                    cfg.tools = tools
            elif line.startswith("canonical"):
                parts = line.split("=", 1)
                if len(parts) == 2:
                    cfg.canonical = parts[1].strip().strip('"').strip("'")
            elif line.startswith("auto_gitignore"):
                cfg.auto_gitignore = "true" in line.lower()
    except Exception:
        pass
    return cfg


def is_initialised(root: Path | None = None) -> bool:
    """Check if agentsync has been initialised in this directory."""
    root = root or Path.cwd()
    return (root / CONFIG_FILE).exists() and (root / RULES_FILE).exists()


def read_rules(root: Path | None = None) -> str:
    """Read the canonical rules file."""
    root = root or Path.cwd()
    rules_path = root / RULES_FILE
    if not rules_path.exists():
        raise FileNotFoundError(
            f"Rules file not found at {rules_path}. " "Run `agentsync init` first."
        )
    return rules_path.read_text(encoding="utf-8")


def write_config(root: Path | None = None, tools: list[str] | None = None) -> None:
    """Write a fresh config file."""
    root = root or Path.cwd()
    config_path = root / CONFIG_FILE
    config_path.parent.mkdir(parents=True, exist_ok=True)
    content = DEFAULT_CONFIG
    if tools:
        tool_list = "\n".join(f'    "{t}",' for t in tools)
        import re

        content = re.sub(
            r"tools = \[.*?\]",
            f"tools = [\n{tool_list}\n]",
            content,
            flags=re.DOTALL,
        )
    config_path.write_text(content, encoding="utf-8")


def write_rules(content: str | None = None, root: Path | None = None) -> None:
    """Write the canonical rules file."""
    root = root or Path.cwd()
    rules_path = root / RULES_FILE
    rules_path.parent.mkdir(parents=True, exist_ok=True)
    rules_path.write_text(content or DEFAULT_RULES, encoding="utf-8")
