"""
Tool definitions and output generators for agentsync.
Each tool has a name, description, output path(s), and a generate function.
Zero external dependencies.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Callable


@dataclass
class Tool:
    """An AI coding tool that reads agent rule files."""

    id: str
    name: str
    output_paths: list[str]
    description: str
    supports_sections: bool = False
    supports_globs: bool = False
    notes: str = ""

    def generate(self, content: str, sections: dict[str, str] | None = None) -> str:
        """Generate the tool-specific output from canonical content."""
        return _generators[self.id](content, sections or {})

    def __repr__(self) -> str:
        return f"Tool({self.id!r}, paths={self.output_paths})"


def _gen_agents_md(content: str, sections: dict[str, str]) -> str:
    """AGENTS.md — the emerging cross-tool standard. Minimal transformation."""
    return content.strip() + "\n"


def _gen_claude_md(content: str, sections: dict[str, str]) -> str:
    """CLAUDE.md for Claude Code. Adds Claude-specific header if not present."""
    if "claude" not in content.lower()[:200]:
        header = "<!-- Generated by agentsync. Edit .agentsync/rules.md, not this file. -->\n\n"
        return header + content.strip() + "\n"
    return content.strip() + "\n"


def _gen_cursorrules(content: str, sections: dict[str, str]) -> str:
    """
    .cursorrules (legacy Cursor format).
    Strips markdown headers since Cursor treats the file as plain instructions.
    """
    lines = content.splitlines()
    output_lines = []
    for line in lines:
        # Convert markdown headers to plain section dividers
        if line.startswith("# "):
            output_lines.append("")
            output_lines.append("=" * 60)
            output_lines.append(line[2:].upper())
            output_lines.append("=" * 60)
        elif line.startswith("## "):
            output_lines.append("")
            output_lines.append(line[3:])
            output_lines.append("-" * len(line[3:]))
        elif line.startswith("### "):
            output_lines.append("")
            output_lines.append(line[4:])
        else:
            output_lines.append(line)
    result = "\n".join(output_lines).strip()
    return f"# Generated by agentsync. Edit .agentsync/rules.md, not this file.\n\n{result}\n"


def _gen_cursor_mdc(content: str, sections: dict[str, str]) -> str:
    """
    .cursor/rules/main.mdc — modern Cursor format with YAML frontmatter.
    """
    frontmatter = "---\ndescription: Project rules and conventions\nalwaysApply: true\n---\n\n"
    note = "<!-- Generated by agentsync. Edit .agentsync/rules.md, not this file. -->\n\n"
    return frontmatter + note + content.strip() + "\n"


def _gen_copilot(content: str, sections: dict[str, str]) -> str:
    """
    .github/copilot-instructions.md for GitHub Copilot.
    Copilot supports markdown natively — minimal transformation.
    """
    header = "<!-- Generated by agentsync. Edit .agentsync/rules.md, not this file. -->\n\n"
    return header + content.strip() + "\n"


def _gen_gemini_md(content: str, sections: dict[str, str]) -> str:
    """GEMINI.md for Gemini CLI. Same format as AGENTS.md."""
    header = "<!-- Generated by agentsync. Edit .agentsync/rules.md, not this file. -->\n\n"
    return header + content.strip() + "\n"


def _gen_windsurf(content: str, sections: dict[str, str]) -> str:
    """
    .windsurfrules for Windsurf.
    Windsurf reads plain markdown — minimal transformation.
    """
    header = "# Generated by agentsync. Edit .agentsync/rules.md, not this file.\n\n"
    return header + content.strip() + "\n"


def _gen_aider(content: str, sections: dict[str, str]) -> str:
    """
    .aider.conf.yml — Aider reads a YAML config, not markdown.
    We extract the relevant sections and write them as YAML comments + conventions.
    """
    lines = [
        "# Generated by agentsync. Edit .agentsync/rules.md, not this file.",
        "# Aider conventions extracted from canonical rules.",
        "",
        "## aider configuration",
        "# model: claude-opus-4-5",
        "# auto-commits: true",
        "",
        "# --- Project rules (from agentsync) ---",
    ]
    for line in content.splitlines():
        lines.append(f"# {line}" if line.strip() else "#")
    return "\n".join(lines) + "\n"


def _gen_opencode(content: str, sections: dict[str, str]) -> str:
    """
    AGENTS.md is natively supported by OpenCode.
    Returns the same output as AGENTS.md.
    """
    return _gen_agents_md(content, sections)


_generators: dict[str, Callable[[str, dict[str, str]], str]] = {
    "agents_md": _gen_agents_md,
    "claude_md": _gen_claude_md,
    "cursorrules": _gen_cursorrules,
    "cursor_mdc": _gen_cursor_mdc,
    "copilot": _gen_copilot,
    "gemini_md": _gen_gemini_md,
    "windsurf": _gen_windsurf,
    "aider": _gen_aider,
    "opencode": _gen_opencode,
}

# ── Tool registry ──────────────────────────────────────────────

ALL_TOOLS: dict[str, Tool] = {
    "agents_md": Tool(
        id="agents_md",
        name="AGENTS.md (cross-tool standard)",
        output_paths=["AGENTS.md"],
        description="Emerging cross-tool standard. Supported by Claude Code, Codex, OpenCode, and most modern tools.",
        supports_sections=True,
        notes="Recommended as the canonical source format.",
    ),
    "claude_md": Tool(
        id="claude_md",
        name="Claude Code (CLAUDE.md)",
        output_paths=["CLAUDE.md"],
        description="Claude Code's native instruction file. Supports hierarchical loading from parent dirs.",
        supports_sections=True,
    ),
    "cursorrules": Tool(
        id="cursorrules",
        name="Cursor (.cursorrules, legacy)",
        output_paths=[".cursorrules"],
        description="Legacy Cursor format. Still supported but .cursor/rules/*.mdc is preferred.",
        notes="Consider migrating to cursor_mdc for new projects.",
    ),
    "cursor_mdc": Tool(
        id="cursor_mdc",
        name="Cursor (.cursor/rules/main.mdc)",
        output_paths=[".cursor/rules/main.mdc"],
        description="Modern Cursor format with YAML frontmatter and glob-pattern scoping.",
        supports_sections=True,
        supports_globs=True,
    ),
    "copilot": Tool(
        id="copilot",
        name="GitHub Copilot",
        output_paths=[".github/copilot-instructions.md"],
        description="GitHub Copilot's repository-wide instruction file.",
    ),
    "gemini_md": Tool(
        id="gemini_md",
        name="Gemini CLI (GEMINI.md)",
        output_paths=["GEMINI.md"],
        description="Gemini CLI's native format. Supports directory traversal — reads up and down the tree.",
    ),
    "windsurf": Tool(
        id="windsurf",
        name="Windsurf (.windsurfrules)",
        output_paths=[".windsurfrules"],
        description="Windsurf's rule file. Plain markdown, project-root scoped.",
    ),
    "aider": Tool(
        id="aider",
        name="Aider (.aider.conf.yml)",
        output_paths=[".aider.conf.yml"],
        description="Aider configuration file. Rules are extracted as YAML comments.",
    ),
    "opencode": Tool(
        id="opencode",
        name="OpenCode (AGENTS.md)",
        output_paths=["AGENTS.md"],
        description="OpenCode reads AGENTS.md natively.",
    ),
}


def get_tool(tool_id: str) -> Tool:
    if tool_id not in ALL_TOOLS:
        raise KeyError(f"Unknown tool {tool_id!r}. Available: {sorted(ALL_TOOLS)}")
    return ALL_TOOLS[tool_id]


def get_tools(tool_ids: list[str]) -> list[Tool]:
    return [get_tool(t) for t in tool_ids]


DEFAULT_TOOLS = [
    "agents_md",
    "claude_md",
    "cursorrules",
    "cursor_mdc",
    "copilot",
    "gemini_md",
    "windsurf",
]
