"""Tests for agentsync. Run: pytest tests/ -v"""

from __future__ import annotations

import json
import sys
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).parent.parent / "src"))

from agentsync import (
    ALL_TOOLS,
    DEFAULT_TOOLS,
    AgentSyncConfig,
    AgentSyncer,
    SyncReport,
    is_initialised,
    load_config,
)
from agentsync.config import (
    CONFIG_FILE,
    LOCK_FILE,
    RULES_FILE,
    read_rules,
    write_config,
    write_rules,
)
from agentsync.tools import (
    _gen_agents_md,
    _gen_claude_md,
    _gen_copilot,
    _gen_cursor_mdc,
    _gen_cursorrules,
    _gen_gemini_md,
    _gen_windsurf,
    get_tool,
    get_tools,
)

SAMPLE_RULES = """# Project Rules

## Stack
- Python 3.11+
- FastAPI
- PostgreSQL

## Conventions
- Use type hints
- Write docstrings
- Follow PEP 8

## Testing
- Run: pytest tests/ -v
- Coverage > 80%
"""


# ── Tool tests ─────────────────────────────────────────────────


class TestTools:
    def test_all_tools_have_ids(self):
        for tid, tool in ALL_TOOLS.items():
            assert tool.id == tid

    def test_all_tools_have_names(self):
        for tool in ALL_TOOLS.values():
            assert tool.name

    def test_all_tools_have_output_paths(self):
        for tool in ALL_TOOLS.values():
            assert len(tool.output_paths) >= 1

    def test_all_tools_have_descriptions(self):
        for tool in ALL_TOOLS.values():
            assert tool.description

    def test_get_tool_valid(self):
        tool = get_tool("claude_md")
        assert tool.id == "claude_md"

    def test_get_tool_invalid_raises(self):
        with pytest.raises(KeyError):
            get_tool("nonexistent_tool")

    def test_get_tools_list(self):
        tools = get_tools(["claude_md", "copilot"])
        assert len(tools) == 2

    def test_default_tools_all_valid(self):
        for tid in DEFAULT_TOOLS:
            assert tid in ALL_TOOLS

    def test_repr(self):
        tool = get_tool("claude_md")
        assert "claude_md" in repr(tool)


class TestGenerators:
    def test_agents_md_passthrough(self):
        result = _gen_agents_md(SAMPLE_RULES, {})
        assert "Project Rules" in result
        assert "Stack" in result

    def test_claude_md_has_header(self):
        result = _gen_claude_md(SAMPLE_RULES, {})
        assert "Generated by agentsync" in result or "Project Rules" in result

    def test_cursorrules_transforms_headers(self):
        result = _gen_cursorrules(SAMPLE_RULES, {})
        assert "Generated by agentsync" in result
        assert "PROJECT RULES" in result.upper() or "Stack" in result

    def test_cursor_mdc_has_frontmatter(self):
        result = _gen_cursor_mdc(SAMPLE_RULES, {})
        assert result.startswith("---")
        assert "alwaysApply" in result

    def test_copilot_has_header(self):
        result = _gen_copilot(SAMPLE_RULES, {})
        assert "Generated by agentsync" in result

    def test_gemini_md_has_content(self):
        result = _gen_gemini_md(SAMPLE_RULES, {})
        assert "Stack" in result

    def test_windsurf_has_content(self):
        result = _gen_windsurf(SAMPLE_RULES, {})
        assert "Stack" in result

    def test_all_generators_return_strings(self):
        for tool in ALL_TOOLS.values():
            result = tool.generate(SAMPLE_RULES)
            assert isinstance(result, str)
            assert len(result) > 0

    def test_all_generators_preserve_content(self):
        for tool in ALL_TOOLS.values():
            result = tool.generate(SAMPLE_RULES)
            assert "Stack" in result or "stack" in result.lower()

    def test_generator_ends_with_newline(self):
        for tool in ALL_TOOLS.values():
            result = tool.generate(SAMPLE_RULES)
            assert result.endswith("\n")


# ── Config tests ───────────────────────────────────────────────


class TestConfig:
    def test_default_config(self):
        cfg = AgentSyncConfig()
        assert len(cfg.tools) > 0
        assert cfg.auto_gitignore is True

    def test_is_initialised_false_when_missing(self, tmp_path):
        assert not is_initialised(tmp_path)

    def test_is_initialised_true_when_present(self, tmp_path):
        write_config(tmp_path)
        write_rules(root=tmp_path)
        assert is_initialised(tmp_path)

    def test_write_config_creates_file(self, tmp_path):
        write_config(tmp_path)
        assert (tmp_path / CONFIG_FILE).exists()

    def test_write_rules_creates_file(self, tmp_path):
        write_rules(root=tmp_path)
        assert (tmp_path / RULES_FILE).exists()

    def test_write_rules_custom_content(self, tmp_path):
        write_rules(content="# Custom Rules\n", root=tmp_path)
        assert "Custom Rules" in (tmp_path / RULES_FILE).read_text()

    def test_read_rules_returns_content(self, tmp_path):
        write_rules(content=SAMPLE_RULES, root=tmp_path)
        assert read_rules(tmp_path) == SAMPLE_RULES

    def test_read_rules_raises_if_missing(self, tmp_path):
        with pytest.raises(FileNotFoundError):
            read_rules(tmp_path)

    def test_load_config_returns_defaults_when_missing(self, tmp_path):
        cfg = load_config(tmp_path)
        assert isinstance(cfg.tools, list)

    def test_load_config_reads_tools(self, tmp_path):
        write_config(tmp_path, tools=["claude_md", "copilot"])
        cfg = load_config(tmp_path)
        assert "claude_md" in cfg.tools

    def test_canonical_path_property(self, tmp_path):
        cfg = AgentSyncConfig(root=tmp_path)
        assert str(cfg.canonical_path).endswith("rules.md")

    def test_config_path_property(self, tmp_path):
        cfg = AgentSyncConfig(root=tmp_path)
        assert str(cfg.config_path).endswith("config.toml")


# ── AgentSyncer tests ──────────────────────────────────────────


class TestAgentSyncer:
    @pytest.fixture
    def project(self, tmp_path):
        write_config(
            tmp_path,
            tools=[
                "claude_md",
                "copilot",
                "gemini_md",
                "cursorrules",
                "cursor_mdc",
                "windsurf",
                "agents_md",
            ],
        )
        write_rules(content=SAMPLE_RULES, root=tmp_path)
        return tmp_path

    def test_sync_returns_report(self, project):
        syncer = AgentSyncer(root=project)
        report = syncer.sync()
        assert isinstance(report, SyncReport)

    def test_sync_creates_files(self, project):
        syncer = AgentSyncer(root=project)
        syncer.sync()
        assert (project / "CLAUDE.md").exists()
        assert (project / ".github/copilot-instructions.md").exists()
        assert (project / "GEMINI.md").exists()
        assert (project / ".cursorrules").exists()
        assert (project / "AGENTS.md").exists()

    def test_sync_created_count(self, project):
        syncer = AgentSyncer(root=project)
        report = syncer.sync()
        assert report.created > 0

    def test_sync_unchanged_on_second_run(self, project):
        syncer = AgentSyncer(root=project)
        syncer.sync()
        report2 = syncer.sync()
        assert report2.unchanged == report2.total
        assert report2.created == 0
        assert report2.updated == 0

    def test_sync_updates_when_rules_change(self, project):
        syncer = AgentSyncer(root=project)
        syncer.sync()
        write_rules(content=SAMPLE_RULES + "\n## New Section\n- New rule", root=project)
        report2 = syncer.sync()
        assert report2.updated > 0

    def test_dry_run_does_not_write(self, project):
        syncer = AgentSyncer(root=project)
        syncer.sync(dry_run=True)
        assert not (project / "CLAUDE.md").exists()

    def test_dry_run_shows_changes(self, project):
        syncer = AgentSyncer(root=project)
        report = syncer.sync(dry_run=True)
        assert report.dry_run is True
        assert report.created > 0

    def test_generated_files_contain_content(self, project):
        syncer = AgentSyncer(root=project)
        syncer.sync()
        claude_md = (project / "CLAUDE.md").read_text()
        assert "Stack" in claude_md or "stack" in claude_md.lower()

    def test_cursor_mdc_has_directory(self, project):
        syncer = AgentSyncer(root=project)
        syncer.sync()
        mdc_path = project / ".cursor/rules/main.mdc"
        assert mdc_path.exists()
        assert "alwaysApply" in mdc_path.read_text()

    def test_lock_file_created(self, project):
        syncer = AgentSyncer(root=project)
        syncer.sync()
        assert (project / LOCK_FILE).exists()

    def test_lock_file_has_hash(self, project):
        syncer = AgentSyncer(root=project)
        syncer.sync()
        lock = json.loads((project / LOCK_FILE).read_text())
        assert "canonical_hash" in lock

    def test_status_all_ok_after_sync(self, project):
        syncer = AgentSyncer(root=project)
        syncer.sync()
        statuses = syncer.status()
        for s in statuses:
            assert s["status"] == "ok", f"{s['path']} is {s['status']}"

    def test_status_stale_before_sync(self, project):
        syncer = AgentSyncer(root=project)
        syncer.sync()
        write_rules(content=SAMPLE_RULES + "\n## Changed", root=project)
        statuses = syncer.status()
        stale = [s for s in statuses if s["status"] == "stale"]
        assert len(stale) > 0

    def test_status_missing_before_sync(self, project):
        syncer = AgentSyncer(root=project)
        statuses = syncer.status()
        missing = [s for s in statuses if s["status"] == "missing"]
        assert len(missing) > 0

    def test_detect_unmanaged(self, project):
        (project / "AGENTS.md").write_text("# Manual rules\n- Do this")
        syncer = AgentSyncer(root=project)
        unmanaged = syncer.detect_unmanaged()
        assert "AGENTS.md" in unmanaged

    def test_detect_unmanaged_empty_after_sync(self, project):
        # Use a minimal tool set to avoid path collisions (agents_md + opencode share AGENTS.md)
        from agentsync.config import write_config

        write_config(project, tools=["claude_md", "copilot", "gemini_md"])
        syncer = AgentSyncer(root=project)
        syncer.sync()
        unmanaged = syncer.detect_unmanaged()
        # After sync, generated files should all have the agentsync header
        for path in unmanaged:
            abs_p = project / path
            if abs_p.exists():
                assert "Generated by agentsync" in abs_p.read_text()

    def test_summary_is_string(self, project):
        syncer = AgentSyncer(root=project)
        report = syncer.sync()
        assert isinstance(report.summary(), str)
        assert "agentsync sync" in report.summary()

    def test_repr_result(self, project):
        syncer = AgentSyncer(root=project)
        report = syncer.sync()
        assert "SyncResult" in repr(report.results[0])

    def test_repr_report(self, project):
        syncer = AgentSyncer(root=project)
        report = syncer.sync()
        assert "SyncReport" in repr(report)

    def test_invalid_tool_in_config(self, tmp_path):
        write_config(tmp_path, tools=["claude_md", "nonexistent_tool"])
        write_rules(content=SAMPLE_RULES, root=tmp_path)
        syncer = AgentSyncer(root=tmp_path)
        report = syncer.sync()
        assert report.errors >= 1

    def test_sync_single_tool(self, tmp_path):
        write_config(tmp_path, tools=["claude_md"])
        write_rules(content=SAMPLE_RULES, root=tmp_path)
        syncer = AgentSyncer(root=tmp_path)
        report = syncer.sync()
        assert report.total == 1
        assert (tmp_path / "CLAUDE.md").exists()

    def test_on_progress_via_verbose(self, project):
        syncer = AgentSyncer(root=project, verbose=True)
        report = syncer.sync()
        assert report.total > 0
